backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: ../../static/images/


collections:
  - name: 'pesme'
    preview: false
    label: 'Pesme'
    folder: 'content/pesme'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: 'Naslov', name: 'title', widget: 'string'}
      - {label: 'Objavljeno', name: 'objavljeno', widget: 'string', required: false}
      - {label: 'Datum', name: 'datum', widget: 'date', format: "D. M. YYYY."}
      - {label: 'Body', name: 'body', widget: 'text'}